openapi: "3.0.0"
info:
  version: 1.0.0
  title: To Do Service API
  license:
    name: MIT
paths:
  /todos:
    get:
      summary: List all todo items
      responses:
        '200':
          description: An array of to do items
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TodoItems"
components:
  schemas:
    TodoItem:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    TodoItems:
      type: array
      items:
        $ref: "#/components/schemas/TodoItem"
