openapi: "3.0.0"
info:
  version: 1.0.0
  title: To Do Service API
  license:
    name: MIT
paths:
  /todos:
    get:
      summary: List all todo items
      operationId: getTodoItems
      responses:
        '200':
          description: An array of todo items
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TodoItems"
    post:
      summary: Create a new todo item
      operationId: createTodoItem
      requestBody:
        description: Create a new todo item
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TodoItem"
      responses:
        '200':
          description: Created todo item
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TodoItem"
components:
  schemas:
    TodoItem:
      type: object
      required:
        - name
        - completed
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        completed:
          type: boolean
    TodoItems:
      type: array
      items:
        $ref: "#/components/schemas/TodoItem"
