apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "todo-service.fullname" . }}-backend-config
spec:
  healthCheck:
    type: HTTP
    requestPath: /actuator/health
    port: 8081
